# ===============================
# APPLICATION
# ===============================
spring.application.name=archivalsys


# ===============================
# DATABASE (Render MySQL)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# AZURE BLOB STORAGE
# ===============================
azure.storage.connection-string=${AZURE_BLOB_CONNECTION_STRING}
azure.storage.container-name=${AZURE_BLOB_CONTAINER}

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ===============================
# MULTIPART FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# FRONTEND (CORS)
# ===============================
frontend.url=${FRONTEND_URL}
